#include <icons/Bells.h>
#include <icons/BigBell.h>
#include <icons/BlueLight.h>
#include <icons/Candycane.h>
#include <icons/Hat.h>
#include <icons/ClearLight.h>
#include <icons/GoldBall.h>
#include <icons/GoldCandle.h>
#include <icons/GoldStar.h>
#include <icons/GreenBall.h>
#include <icons/GreenCandle.h>
#include <icons/GreenCandle-2.h>
#include <icons/GreenLight.h>
#include <icons/Holly-1.h>
#include <icons/Holly-2.h>
#include <icons/Present-1.h>
#include <icons/Present-2.h>
#include <icons/Present-3.h>
#include <icons/Present-4.h>
#include <icons/Present-5.h>
#include <icons/PurpleBall.h>
#include <icons/Reindeer.h>
#include <icons/Reindeers.h>
#include <icons/RedBall.h>
#include <icons/RedCandle.h>
#include <icons/RedCandle-2.h>
#include <icons/RedLight.h>
#include <icons/Santa.h>
#include <icons/SilverBall.h>
#include <icons/SilverCandle.h>
#include <icons/SilverStar.h>
#include <icons/Sled.h>
#include <icons/SnowGlobe-Penguin.h>
#include <icons/SnowGlobe-Tree.h>
#include <icons/Snowman.h>
#include <icons/Stocking.h>
#include <icons/Tree-1.h>
#include <icons/Tree-2.h>
#include <icons/WhiteCandle.h>
#include <icons/WoodenBall.h>
#include <icons/Wreath-1.h>
#include <icons/Wreath-2.h>
#include <icons/Wreath-3.h>
#include <icons/YellowLight.h>
